O módulo assert fornece um conjunto de funções de asserção para verificar invariantes. A função assert.doesNotThrow() assegura que a função fn não gera erro. Sintaxe:
```
assert.doesNotThrow(fn[, error][, message])
```

Parâmetros: Esta função aceita os seguintes parâmetros, conforme mencionado acima e descritos abaixo:
fn: Este parâmetro é uma função que não gera erro.
erro: Este parâmetro é uma expressão regular ou função. É o erro especificado. É um parâmetro opcional.
mensagem: Este parâmetro contém a mensagem de erro do tipo string ou erro. É um parâmetro opcional.

Valor de retorno: Esta função retorna um erro de asserção do tipo objeto. Instalação do módulo assert:
Você pode acessar o link para Instalar o módulo assert . Você pode instalar este pacote usando este comando.
```
npm install assert
```
Observação: a instalação é uma etapa opcional, pois é um módulo integrado do Node.js.
Após instalar o módulo assert, você pode verificar sua versão assert no prompt de comando usando o comando.
```
npm version assert
```
Depois disso, você pode simplesmente criar uma pasta e adicionar um arquivo, por exemplo, index.js, conforme mostrado abaixo.

### Exemplo 1: Nome do arquivo: index.js
```node
// Requiring the module
const assert = require('assert').strict;

// Function call
try {
    assert.doesNotThrow(
        () => {
          throw new TypeError('Wrong value');
        },
    );
} catch(error) {
    console.log("Error:", error)
}
```

Etapas para executar o programa:
A estrutura do projeto ficará assim:
  
![](https://media.geeksforgeeks.org/wp-content/uploads/20200606171437/structure56.png)

Execute o arquivo index.js usando o comando abaixo:
```
node index.js
```

Saída:
```
Error: AssertionError [ERR_ASSERTION]: Got unwanted exception.
Actual message: "Wrong value"
    at Object. (C:\Users\Lenovo\Downloads\index.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: TypeError: Wrong value
      at C:\Users\Lenovo\index.js:8:17
      at getActual (assert.js:657:5)
      at Function.doesNotThrow (assert.js:805:32)
      at Object. (C:\Users\NEW\Assert Function\index.js:6:12)
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
      at Module.load (internal/modules/cjs/loader.js:986:32)
      at Function.Module._load (internal/modules/cjs/loader.js:879:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47,
  expected: undefined,
  operator: 'doesNotThrow'
}
```


### Example 2: Filename: index.js

```node
// Requiring the module
const assert = require('assert').strict;

// Function call
try {
    assert.doesNotThrow(
        () => {
          throw new TypeError('The Wrong value error');
        },
        /abcd/,
        'Whoops'
    );
} catch(error) {
    console.log("Error:", error)
}
```

Etapas para executar o programa:
A estrutura do projeto ficará assim:    ![](https://media.geeksforgeeks.org/wp-content/uploads/20200606171437/structure56.png)

Execute o arquivo index.js usando o comando abaixo:
```
node index.js
```

Saída:
```
Error: TypeError: The Wrong value error
    at C:\Users\Lenovo\Downloads\Geeksforgeeks Internship\NEW\Assert\index.js:8:17
    at getActual (assert.js:657:5)
    at Function.doesNotThrow (assert.js:805:32)
    at Object. (C:\Internship\NEW\Assert Function\index.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Referência: https://nodejs.org/dist/latest-v12.x/docs/api/assert.html#assert_assert_doesnotthrow_fn_error_message

